### ISSUE TITLE
se -> sv is it ok?

### ISSUE THREAD

**Issue by aLkRicha** [misd-service-development/phone-number-bundle#164]
Hello, in lates release you moved se cc to sv.
But 2d ISO code is SE:
https://countrycode.org/sweden

**Comment by rh389** [comment]
Interesting - ping @jongotlin. I think `sv` is correct because translations should use _language_ codes (ISO 639) rather than _country_ codes (ISO 3166), but I don't know if there's a rule about that anywhere - the Symfony docs don't mention anything about it and the XLIFF spec doesn't seem to mention it either.

Apologies for the unintentional breaking change though (we probably should've duplicated `se` into `sv` and deprecated the former).

**Comment by jongotlin** [comment]
`sv` is indeed correct and deprecation would've been a better solution (is there a way to deprecate language files?). 

@aLkRicha, do you use `se` as locale on your project? Are there any other bundles using `se` in their translation files? This is the first time I encounter it. 

Should we re-add the `sv` file and remove at next major release?

**Comment by rh389** [comment]
> is there a way to deprecate language files?

No technical way to mark them deprecated AFAIK, but I can put something in the release notes.

> Should we re-add the `sv` file and remove at next major release?

Yeah I think re-adding `se` and issuing a patch release is the way to go.

PRs welcome, otherwise I'll try to sort this out tomorrow.
